config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/home' => 'pages#home', as: :home
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'signups#new', as: :contact
  get '/thanks' => 'pages#thanks', as: :thanks

  resources :signups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

    def thanks
    end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
    # Creates a new signup object
    def new
        @signup = Signup.new
    end

    def create
        @signup = Signup.new(signup_params)
        if @signup.save
            redirect_to thanks_path
        end
    end

    private
    def signup_params
        params.require(:signup).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stories2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Navigation Menu -->
    <div class="menu">
        <ul>
            <li><a href="home">Home</a></li>
            <li><a href="about">About</a></li>
            <li><a href="contact">Contact</a></li>
        </ul>
        <img class="icon-close" src="/assets/close-white.svg" width=25px>
    </div>

    <!-- Page Content -->
    <%= yield %>

    <!-- Footer -->
    <div class="footer">
      <div class="container">
        <p>A Matthew Yerkes Project</p>
      </div>
    </div>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'menu' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-main">
    <img class="icon-menu" src="/assets/menu-white.svg" width=50px>
    <div class="container">
        <h1>Relive your favorite moments</h1>
    </div>
</div>
<div class="about-supporting">
    <div class="container">
        <h2>No more sorting through photos</h2>
        <p>Stories automatically finds your best photos and creates a new travel journal. That way you can capture and share your special moments in fresh new ways.</p>
        <p><%= link_to "Sign up", contact_path, :class=>"btn btn-primary" %></p>
    </div>
</div>

app/views/pages/contact.html.erb
<!-- do not use -->

app/views/pages/home.html.erb
<div class="home-main">
    <img class="icon-menu" src="/assets/menu-white.svg" width=50px>
    <div class="container">
        <div class="row">
            <div class="content"> 
                <h1>Create and share Stories</h1> 
                <p><%= link_to "Learn more", about_path, :class=>"btn btn-primary" %></p>
            </div>
        </div>
    </div>
</div>
<div class="home-supporting">
    <div class="container">
        <h2>Relive and share your adventures</h2>
        <p>Stories automatically creates a digital journal filled with only your best photos.</p>
    </div>
</div>
<div class="home-secondary">
    <div class="container">
    </div>
</div>
<div class="home-about">
    <div class="container">
        <h2>Discover More</h2>
        <p><%= link_to "Learn more", about_path, :class=>"btn btn-primary" %></p>
    </div>
</div>

app/views/pages/thanks.html.erb
<div class="thanks-main">
    <img class="icon-menu" src="/assets/menu-white.svg" width=50px>
    <div class="container">
        <h1>Thanks for reaching out!</h1>
    </div>
</div>

app/views/signups/new.html.erb
<div class="contact-main">
    <img class="icon-menu" src="/assets/menu-white.svg" width=50px>
    <div class="container">
        <h1>Contact us</h1>
    </div>
</div>

<div class="contact-supporting">
    <div class="container">
        <%= form_for(@signup) do |signup| %>
        <%= signup.text_field :firstname, :placeholder => "First Name" %>
        <%= signup.text_field :lastname, :placeholder => "Last Name" %>
        <%= signup.text_field :email, :placeholder => "Email" %>
        <%= signup.submit "Submit", :class => "btn btn-primary" %>
        <% end %>
    </div>
</div>